#!/usr/bin/python3

import sys
from requests_tor import RequestsTor
import requests
from bs4 import BeautifulSoup
import html2text


if len(sys.argv) != 2:
    print('\nUsage:speedguide [port]\n')
    sys.exit()

port = sys.argv[1] # set this var so we can check for correct input later
url = 'https://www.speedguide.net/port.php?port=' + str(port)
# Don't forget to set your password
rt = RequestsTor(tor_ports=(9000,9001,9002,9003), tor_cport=(9151), password=None,
                autochange_id=5, threads=8, verbose=True)
"""
# test
print(requests.get('https://httpbin.org/ip').text)
rt.check_ip()
rt.new_id()   # new tor identity.
"""
rt.check_ip()
rt.new_id()   # new tor identity.
soup = BeautifulSoup(rt.get(url).content, 'html.parser')
table = soup.find('table', class_='port')
print(html2text.html2text(str(table)))
